workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set gradlew permissions
        script: |
          chmod +x $CM_BUILD_DIR/gradlew
      - name: Check available tasks
        script: |
          cd $CM_BUILD_DIR
          ./gradlew :shared:tasks --all 2>&1 | grep -i "xcframework" || echo "Brak xcframework tasks"
          ./gradlew :shared:tasks --all 2>&1 | grep -i "assemble" || echo "Brak assemble tasks"